#!/usr/bin/env python3
"""
Convert custom object demonstration trajectories to the DP3-compatible format.

This script takes raw demonstration data generated by gen_demo_custom.py
and converts it to the pickle format expected by the ArticuBot training pipeline.

IMPORTANT: Only demos with the following files will be processed:
- all.gif (indicates successful demo)
- stage_lengths.json (timing information)
- states/ folder with state_*.pkl files

Usage:
    python scripts/custom_finetune/convert_custom_demos.py \
        --input-dir data/custom_objects/sim_microwave_good/experiment/traj_100 \
        --output-dir data/custom_finetune/sim_microwave_traj_100 \
        --env-name articulated_custom_object
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import pathlib
from termcolor import cprint

# Add project root to path
PROJECT_DIR = pathlib.Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(PROJECT_DIR))


def parse_args():
    parser = argparse.ArgumentParser(
        description="Convert custom demos to DP3 training format"
    )
    parser.add_argument(
        "--input-dir",
        type=str,
        required=True,
        help="Path to experiment folder containing demo trajectories (e.g., experiment/traj_100)"
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        required=True,
        help="Output directory for converted demos (e.g., data/custom_finetune/my_object)"
    )
    parser.add_argument(
        "--env-name",
        type=str,
        default="articulated_custom_object",
        help="Environment name"
    )
    parser.add_argument(
        "--pointcloud-num",
        type=int,
        default=4500,
        help="Number of points in point cloud"
    )
    parser.add_argument(
        "--combine-action-steps",
        type=int,
        default=2,
        help="Combine consecutive action steps"
    )
    parser.add_argument(
        "--min-opened-ratio",
        type=float,
        default=0.2,
        help="Minimum opening ratio to consider trajectory successful"
    )
    parser.add_argument(
        "--num-experiment",
        type=int,
        default=10000,
        help="Maximum number of experiments to process"
    )
    parser.add_argument(
        "--randomize-camera",
        type=int,
        default=0,
        help="Randomize camera (0 or 1)"
    )
    parser.add_argument(
        "--noise-real-world-pcd",
        type=int,
        default=0,
        help="Add real-world noise to point cloud (0 or 1)"
    )
    parser.add_argument(
        "--real-world-camera",
        type=int,
        default=0,
        help="Use real-world camera settings (0 or 1)"
    )
    return parser.parse_args()


def check_valid_demo(demo_path: pathlib.Path) -> bool:
    """Check if a demo folder has all required files for conversion."""
    required = [
        demo_path / "all.gif",
        demo_path / "stage_lengths.json",
        demo_path / "task_config.yaml",
    ]
    states_dir = demo_path / "states"
    
    # Check required files exist
    for req in required:
        if not req.exists():
            return False
    
    # Check states directory has files
    if not states_dir.exists():
        return False
    
    state_files = list(states_dir.glob("state_*.pkl"))
    return len(state_files) > 0


def main():
    args = parse_args()
    
    input_path = pathlib.Path(args.input_dir).resolve()
    output_path = pathlib.Path(args.output_dir).resolve()
    
    if not input_path.exists():
        raise FileNotFoundError(f"Input directory not found: {input_path}")
    
    # Count valid demos
    subdirs = [d for d in input_path.iterdir() if d.is_dir()]
    valid_demos = [d for d in subdirs if check_valid_demo(d)]
    
    cprint(f"Found {len(subdirs)} subdirectories", "cyan")
    cprint(f"  Valid demos (with all.gif, stage_lengths.json, and states/): {len(valid_demos)}", "green")
    
    if len(valid_demos) == 0:
        cprint("\nNo valid demos found!", "red")
        cprint("Make sure demos have:", "yellow")
        cprint("  - all.gif (indicates successful execution)", "yellow")
        cprint("  - stage_lengths.json (timing information)", "yellow")
        cprint("  - states/ folder with state_*.pkl files", "yellow")
        return
    
    # Determine folder structure
    meta_info_path = input_path / "meta_info.json"
    if meta_info_path.exists():
        with open(meta_info_path, "r") as f:
            meta_info = json.load(f)
        exp_name = input_path.name
        
        # Navigate up to find the actual folder structure
        if input_path.parent.name == "experiment":
            solution_path = input_path.parent.parent
        else:
            solution_path = input_path.parent
    else:
        solution_path = input_path.parent.parent
        exp_name = input_path.name
    
    # Create output directory
    output_path.mkdir(parents=True, exist_ok=True)
    
    print(f"\n{'='*60}")
    print(f"Input path: {input_path}")
    print(f"Output path: {output_path}")
    print(f"Solution path: {solution_path}")
    print(f"Experiment name: {exp_name}")
    print(f"Valid demos to process: {len(valid_demos)}")
    print(f"{'='*60}\n")
    
    # Set up extraction arguments as module-level args
    from argparse import Namespace
    import manipulation.extract_pcd_from_states as extract_module
    
    extract_module.args = Namespace(
        pointcloud_num=args.pointcloud_num,
        observation_mode='act3d_goal_displacement_gripper_to_object',
        filter_close_zero_action=1,
        min_finger_angle_diff=0.001,
        close_gripper_action=-0.006,
        combine_action_steps=args.combine_action_steps,
        min_opened_ratio=args.min_opened_ratio,
        randomize_camera=args.randomize_camera,
        noise_real_world_pcd=args.noise_real_world_pcd,
        real_world_camera=args.real_world_camera,
        num_experiment=args.num_experiment
    )
    
    # Run extraction using custom extraction function for custom objects
    from manipulation.custom_object_utils.extract_pcd_from_states_custom import (
        extract_demos_from_a_directory_custom
    )
    
    # Determine the correct folder and extract name
    folder_name = str(solution_path.parent)
    extract_name = solution_path.name
    
    print(f"Folder name: {folder_name}")
    print(f"Extract name: {extract_name}")
    
    extract_demos_from_a_directory_custom(
        directory_path=folder_name,
        exp_name=exp_name,
        env_name=args.env_name,
        extract_name=extract_name,
        save_path=str(output_path),
        args=extract_module.args,
    )
    
    # Count output files
    output_subdirs = [d for d in output_path.iterdir() if d.is_dir() and not d.name.startswith(('demo_rgbs', 'example_pointcloud'))]
    
    print(f"\n{'='*60}")
    cprint(f"✓ Conversion complete!", "green")
    print(f"  Output saved to: {output_path}")
    print(f"  Converted demos: {len(output_subdirs)}")
    print(f"\n  Use this path as zarr_path/dataset_path for training:")
    print(f"    {output_path}")
    print(f"{'='*60}")


if __name__ == "__main__":
    main()
